### ISSUE TITLE
Adapt footer structure

### ISSUE THREAD

**Issue by WilliamRagstad** [WilliamRagstad/IV1201-Project#3]
Fix the merged branch #2 to use footer classes.

For example here: https://github.com/WilliamRagstad/IV1201-Project/blob/134a5ee5588a66565f031c6b3c8968099d6cf323/recruitment-app/components/footer.tsx#L8

**Comment by Willgar** [comment]
Pull request available here https://github.com/WilliamRagstad/IV1201-Project/pull/4
